import { Product, Category, Review, Order, User } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Makanan Ringan', icon: '🍿', color: '#FF6B6B' },
  { id: '2', name: 'Minuman', icon: '🥤', color: '#4ECDC4' },
  { id: '3', name: 'Kue & Dessert', icon: '🍰', color: '#FFE66D' },
  { id: '4', name: 'Makanan Berat', icon: '🍛', color: '#95E1D3' },
  { id: '5', name: 'Seafood', icon: '🦐', color: '#F38181' },
  { id: '6', name: 'Sayuran', icon: '🥗', color: '#AA96DA' },
  { id: '7', name: 'Buah-buahan', icon: '🍎', color: '#FCBAD3' },
  { id: '8', name: 'Frozen Food', icon: '🧊', color: '#A8D8EA' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Keripik Kentang Original',
    price: 25000,
    originalPrice: 35000,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
    images: [
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
      'https://images.unsplash.com/photo-1599493356626-4575c39a8ae7?w=400',
    ],
    description: 'Keripik kentang renyah dengan rasa original yang gurih. Dibuat dari kentang pilihan berkualitas tinggi.',
    category: 'Makanan Ringan',
    rating: 4.8,
    reviewCount: 128,
    soldCount: 2500,
    isPromo: true,
    isBestSeller: true,
    discount: 29,
    stock: 100,
    variants: [
      { id: 'v1', name: 'Original', price: 25000, stock: 50 },
      { id: 'v2', name: 'BBQ', price: 27000, stock: 30 },
      { id: 'v3', name: 'Keju', price: 28000, stock: 20 },
    ],
  },
  {
    id: '2',
    name: 'Kopi Arabika Aceh Gayo',
    price: 85000,
    originalPrice: 100000,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    description: 'Kopi Arabika premium dari Aceh Gayo dengan cita rasa khas. Sangat cocok untuk pecinta kopi sejati.',
    category: 'Minuman',
    rating: 4.9,
    reviewCount: 89,
    soldCount: 1200,
    isPromo: true,
    discount: 15,
    stock: 50,
  },
  {
    id: '3',
    name: 'Cheesecake Oreo',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1565958011703-1f0beb1cf45e?w=400',
    description: 'Cheesecake lembut dengan topping Oreo yang crunchy. Perfect untuk dessert atau hadiah.',
    category: 'Kue & Dessert',
    rating: 4.7,
    reviewCount: 156,
    soldCount: 890,
    isBestSeller: true,
    stock: 30,
  },
  {
    id: '4',
    name: 'Nasi Goreng Spesial',
    price: 35000,
    originalPrice: 40000,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    description: 'Nasi goreng dengan bumbu rahasia dan topping lengkap: ayam, telur, dan kerupuk.',
    category: 'Makanan Berat',
    rating: 4.6,
    reviewCount: 234,
    soldCount: 3200,
    isPromo: true,
    discount: 12,
    stock: 40,
  },
  {
    id: '5',
    name: 'Udang Windu Fresh',
    price: 120000,
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400',
    description: 'Udang windu segar ukuran jumbo. Dipetik langsung dari tambak berkualitas.',
    category: 'Seafood',
    rating: 4.8,
    reviewCount: 67,
    soldCount: 450,
    stock: 25,
  },
  {
    id: '6',
    name: 'Salad Sayur Segar',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    description: 'Mix sayur segar dengan dressing spesial. Sehat dan lezat!',
    category: 'Sayuran',
    rating: 4.5,
    reviewCount: 98,
    soldCount: 670,
    stock: 35,
  },
  {
    id: '7',
    name: 'Smoothie Bowl Buah',
    price: 32000,
    originalPrice: 38000,
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=400',
    description: 'Smoothie bowl dengan aneka buah segar dan granola. Perfect untuk sarapan sehat.',
    category: 'Buah-buahan',
    rating: 4.7,
    reviewCount: 112,
    soldCount: 780,
    isPromo: true,
    discount: 16,
    stock: 20,
  },
  {
    id: '8',
    name: 'Dimsum Frozen Pack',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400',
    description: 'Dimsum frozen siap kukus dengan 5 varian rasa. Praktis dan enak!',
    category: 'Frozen Food',
    rating: 4.6,
    reviewCount: 145,
    soldCount: 1500,
    isBestSeller: true,
    stock: 60,
  },
  {
    id: '9',
    name: 'Boba Milk Tea',
    price: 22000,
    image: 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=400',
    description: 'Milk tea dengan boba chewy yang kenyal. Pilihan rasa: Original, Taro, atau Matcha.',
    category: 'Minuman',
    rating: 4.8,
    reviewCount: 203,
    soldCount: 2100,
    stock: 45,
    variants: [
      { id: 'v1', name: 'Original', price: 22000, stock: 20 },
      { id: 'v2', name: 'Taro', price: 24000, stock: 15 },
      { id: 'v3', name: 'Matcha', price: 25000, stock: 10 },
    ],
  },
  {
    id: '10',
    name: 'Brownies Fudgy',
    price: 38000,
    originalPrice: 45000,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400',
    description: 'Brownies fudgy dengan tekstur lembut dan rasa coklat yang intens.',
    category: 'Kue & Dessert',
    rating: 4.9,
    reviewCount: 178,
    soldCount: 1350,
    isPromo: true,
    discount: 16,
    stock: 40,
  },
  {
    id: '11',
    name: 'Sate Ayam Madura',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=400',
    description: 'Sate ayam dengan bumbu kacang khas Madura. Dilengkapi lontong.',
    category: 'Makanan Berat',
    rating: 4.7,
    reviewCount: 189,
    soldCount: 980,
    stock: 30,
  },
  {
    id: '12',
    name: 'Kepiting Soka',
    price: 150000,
    originalPrice: 175000,
    image: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400',
    description: 'Kepiting soka segar siap masak. Daging lebat dan manis.',
    category: 'Seafood',
    rating: 4.8,
    reviewCount: 45,
    soldCount: 230,
    isPromo: true,
    discount: 14,
    stock: 15,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    userName: 'Budi Santoso',
    rating: 5,
    comment: 'Produknya sangat enak dan fresh! Pengiriman juga cepat.',
    date: '2024-01-15',
  },
  {
    id: '2',
    userName: 'Ani Wijaya',
    rating: 4,
    comment: 'Enak, tapi kemasannya perlu diperbaiki biar lebih aman.',
    date: '2024-01-14',
  },
  {
    id: '3',
    userName: 'Dedi Kurniawan',
    rating: 5,
    comment: 'Sudah 3x beli disini, tidak pernah kecewa. Recommended!',
    date: '2024-01-13',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    items: [
      { product: products[0], quantity: 2 },
      { product: products[2], quantity: 1 },
    ],
    total: 95000,
    status: 'delivered',
    date: '2024-01-15',
    customerName: 'John Doe',
  },
  {
    id: 'ORD-002',
    items: [
      { product: products[1], quantity: 1 },
    ],
    total: 85000,
    status: 'processing',
    date: '2024-01-16',
    customerName: 'Jane Smith',
  },
  {
    id: 'ORD-003',
    items: [
      { product: products[4], quantity: 2 },
      { product: products[6], quantity: 3 },
    ],
    total: 336000,
    status: 'pending',
    date: '2024-01-16',
    customerName: 'Mike Johnson',
  },
];

export const users: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@foodstore.com', role: 'admin' },
  { id: '2', name: 'John Doe', email: 'john@example.com', role: 'customer' },
  { id: '3', name: 'Jane Smith', email: 'jane@example.com', role: 'customer' },
];

export const heroSlides = [
  {
    id: 1,
    title: 'Makanan Segar Setiap Hari',
    subtitle: 'Diskon hingga 50% untuk produk fresh',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200',
    cta: 'Beli Sekarang',
    color: '#03AC0E',
  },
  {
    id: 2,
    title: 'Promo Spesial Weekend',
    subtitle: 'Free Ongkir untuk minimal pembelian 100rb',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200',
    cta: 'Lihat Promo',
    color: '#00AA5B',
  },
  {
    id: 3,
    title: 'Koleksi Dessert Terbaru',
    subtitle: 'Temukan berbagai dessert lezat dan manis',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=1200',
    cta: 'Jelajahi',
    color: '#F97316',
  },
];
